/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as JourneysIndexRouteImport } from './routes/journeys/index'
import { Route as JourneysNodeIdRouteImport } from './routes/journeys/$nodeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysIndexRoute = JourneysIndexRouteImport.update({
  id: '/journeys/',
  path: '/journeys/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysNodeIdRoute = JourneysNodeIdRouteImport.update({
  id: '/journeys/$nodeId',
  path: '/journeys/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/settings': typeof SettingsRoute
  '/journeys/$nodeId': typeof JourneysNodeIdRoute
  '/journeys/': typeof JourneysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/settings': typeof SettingsRoute
  '/journeys/$nodeId': typeof JourneysNodeIdRoute
  '/journeys': typeof JourneysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/settings': typeof SettingsRoute
  '/journeys/$nodeId': typeof JourneysNodeIdRoute
  '/journeys/': typeof JourneysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/app' | '/settings' | '/journeys/$nodeId' | '/journeys/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/app' | '/settings' | '/journeys/$nodeId' | '/journeys'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/settings'
    | '/journeys/$nodeId'
    | '/journeys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  SettingsRoute: typeof SettingsRoute
  JourneysNodeIdRoute: typeof JourneysNodeIdRoute
  JourneysIndexRoute: typeof JourneysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/': {
      id: '/journeys/'
      path: '/journeys'
      fullPath: '/journeys/'
      preLoaderRoute: typeof JourneysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/$nodeId': {
      id: '/journeys/$nodeId'
      path: '/journeys/$nodeId'
      fullPath: '/journeys/$nodeId'
      preLoaderRoute: typeof JourneysNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  SettingsRoute: SettingsRoute,
  JourneysNodeIdRoute: JourneysNodeIdRoute,
  JourneysIndexRoute: JourneysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
